<?php require_once 'start_html.php'; ?>

<div class="row">
    <div class="col-md-10 col-md-offset-1 well table-responsive">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th class="col-md-10"> Nom </th>
                    <th class="col-md-2"> Action </th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($rosters as $key => $roster) : ?>
                    <tr>
                        <td class="col-md-10"><?php echo $roster['name'] ?></td>
                        <td class="col-md-2">
                            <div class="col-md-4">
                                <a href="<?php echo CFG_PATH_HTTP . '/roster/view_roster.php?id=' . $roster['roster_id'] ?>">
                                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                                </a>
                            </div>

                            <?php if ($roster['admin'] == 1) : ?>
                                <div class="col-md-4">
                                    <a href="<?php echo CFG_PATH_HTTP . '/roster/edit_roster.php?id=' . $roster['roster_id'] ?>">
                                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                    </a>
                                </div>

                                <div class="col-md-4">
                                    <a href="<?php echo CFG_PATH_HTTP . '/roster/del_roster.php?id='  . $roster['roster_id'] ?>">
                                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                    </a>
                                </div>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

        <a href="<?php echo CFG_PATH_HTTP . '/roster/add_roster.php' ?>" class="btn btn-primary pull-right">Ajouter un roster </a>
    </div>
</div>

<?php require_once 'stop_html.php'; ?>