<?php require_once 'start_html.php'; ?>

<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <table class="table">
            <tr>
                <th class="col-md-10"> Nom </th>
                <th class="col-md-2"> Action </th>
            </tr>

            <?php foreach ($rosters as $key => $roster) : ?>
                <tr>
                    <td class="col-md-10"><?php echo $roster['name'] ?></td>
                    <td class="col-md-2">
                        <a href="<?php echo CFG_PATH_HTTP . '/roster/view_roster.php?id=' . $roster['roster_id'] ?>">Voir</a>
                        <a href="<?php echo CFG_PATH_HTTP . '/roster/edit_roster.php?id=' . $roster['roster_id'] ?>">Edit</a>
                        <a href="<?php echo CFG_PATH_HTTP . '/roster/index.php?action=del&id='  . $key ?>">Supprimer</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>

<?php require_once 'stop_html.php'; ?>