<?php require_once 'start_html.php'; ?>

<div class="row">
    <div class="col-md-10 col-md-offset-1 text-center">
        <h1><?php echo $roster['name']; ?></h1>
    </div>
</div>

<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <table class="table table-striped table-hover table-bordered">
            <thead>
                <tr>
                    <th class="col-md-2">Nom</th>

                    <th class="col-md-1 text-center">Level</th>

                    <th class="col-md-1 text-center">ilvl</th>

                    <th class="col-md-7 text-center">&nbsp;</th>

                    <th class="col-md-1 text-center">Classe</th>
                </tr>
            </thead>

            <tbody>
                <?php foreach ($roster_characters as $key => $character) : ?>
                    <tr>
                        <td class="col-md-2 valign"><?php echo $character['name']; ?></td>

                        <td class="col-md-1 text-center valign"><?php echo $character['level']; ?></td>

                        <td class="col-md-1 text-center valign">
                            <?php echo (!empty($character['ilvl']) ? view_ilvl($character['ilvl']) : 'n/a') ?>
                        </td>

                        <td class="col-md-7 valign">&nbsp;</td>

                        <td class="col-md-1 text-center valign">
                            <span class="classicon classicon-<?php echo $character['class_id'] ?>"></span>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

        <button type="button" class="btn btn-primary pull-right" data-toggle="modal" data-target="#modal-add-character">Ajouter</button>
    </div>
</div>

<!-- Modal Add Character-->
<div class="modal fade" id="modal-add-character" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Ajouter un personnage</h4>
            </div>

            <div class="modal-body">
                <div class="row">
                    <form class="form" id="form-add-character">
                        <input type="hidden" name="roster_id" value="<?php echo $_GET['id'] ?>">
                        <div class="form-group col-md-6">
                            <select name="realm" class="form-control">
                                <?php foreach ($realms as $realm): ?>
                                    <option value="<?php echo $realm['name'] ?>">
                                        <?php echo $realm['name'] ?>
                                    </option>
                                <?php endforeach ?>
                            </select>
                        </div>

                        <div class="form-group col-md-6">
                            <input type="text" value="" name="name" class="form-control">
                        </div>
                    </form>
                </div>
                <div class="row">
                    <div class="col-md-12 hidden" id="add-character-error-message"/>
                </div>

            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
                <button type="button" class="btn btn-primary" id="btn-add-character">Ajouter le personnage</button>
            </div>
        </div>
    </div>
</div>

<script>
    $(function() {
        $('#btn-add-character').on('click', function() {
            var data = $('#form-add-character').serialize();

            // Chargement du personnage par Ajax
            $.ajax({
                url: 'ajax/ajax_add_character_roster.php',
                type: 'POST',
                data: data,
                success: function(response, statut) {
                    // Update list à faire
                    $('#modal-add-character').modal('hide');
                    location.reload();

                },
                error : function(response, statut, error) {
                    // Case of fail
                    switch (response.status) {
                        case 422:
                            $('[name=realm]').closest('.form-group').addClass('has-error');
                            $('[name=name]').closest('.form-group').addClass('has-error');

                            $('#add-character-error-message').text('Champs obligatoires manquants');
                            $('#add-character-error-message').removeClass('hidden');
                            break;
                        case 404:
                            $('#add-character-error-message').text('Personnage introuvable');
                            $('#add-character-error-message').removeClass('hidden');
                            break;
                        case 409:
                            $('#add-character-error-message').text('Personnage déjà présent dans le roster');
                            $('#add-character-error-message').removeClass('hidden');
                            break;
                    }
                },
                complete : function(resultat, statut) {

                },
            });
        });
    });
</script>

<?php require_once 'stop_html.php'; ?>