<?php require_once 'start_html.php'; ?>

<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <form class="well clearfix" method="POST" action="">
            <div class="form-group">
                <label for="name_roster">Nom du roster : </label>
                <input type="text" class="form-control" id="name_roster" name="name_roster" placeholder="Nom du roster">
            </div>

            <button type="submit" class="btn btn-primary pull-right">Envoyer</button>
        </form>
    </div>
</div>


<?php require_once 'stop_html.php'; ?>