<?php require_once 'start_html.php'; ?>

<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<?php if (!empty($error)) : ?>
			<div class="alert alert-danger alert-dismissible" role="alert">
	            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
	                <span aria-hidden="true">&times;</span>
	            </button>
	            <ul>
	                <?php foreach ($error as $key => $value) : ?>
	                    <li> <?php echo $value ?></li>
	                <?php endforeach; ?>
	            </ul>
	        </div>
	    <?php endif;?>

		 <form class="form-horizontal clearfix" action="" method="POST">
            <div class="form-group">
                <label for="username" class="col-md-2 control-label">Nom d'utilisateur</label>
                <div class="col-md-10">
                    <input
                    	name="username"
                    	type="text"
                    	value="<?php echo (!empty($_POST['username']) ? $_POST['username'] : '') ?>"
                    	class="form-control"
                    	placeholder="Nom d'utilisateur"
                    >
                </div>
            </div>
            <div class="form-group">
                <label for="password" class="col-md-2 control-label">Mot de passe</label>
                <div class="col-md-10">
                    <input
                    	name="password"
                    	type="password"
                    	value="<?php echo (!empty($_POST['password']) ? $_POST['password'] : '') ?>"
                    	class="form-control"
                    	placeholder="Mot de passe"
                    >
                </div>
            </div>

			<div class="form-group">
                <div class="col-md-10 col-md-offset-2">
                    <button type="submit" class="btn btn-primary btn-block">Se connecter</button>
                </div>
            </div>
       	</form>
	</div>
</div>

<?php require_once 'stop_html.php'; ?>