<?php require_once 'start_html.php' ?>

<pre>
    <?php var_dump($character['stats']) ?>
</pre>

<div class="row">
    <div class="col-md-12">
        <div class="well">
            <table>
                <tbody>
                    <tr>
                        <td rowspan="2">
                            <img class="img-thumbnail character-thumbnail" src="http://render-api-eu.worldofwarcraft.com/static-render/eu/<?php echo $character['thumbnail'] ?>" />
                        </td>

                        <td>
                            <span class="character-name"><?php echo $character['name'] ?></span>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <span class="character-guild"><?php echo $character['name'] ?></span>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <div class="well">
            <table class="table">
                <tbody>
                    <tr>
                        <td width="100px">
                            <span>Vie</span>
                        </td>
                        <td>
                            <div class="progress character-ilvl-progress">
                                <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 100%;">
                                    <?php echo $character['stats']['health'] ?>
                                </div>
                            </div>
                        </td>
                    </tr>

                    <tr>
                        <td width="100px">
                            <span><?php echo $character['stats']['powerType'] ?></span>
                        </td>
                        <td>
                            <div class="progress character-ilvl-progress">
                                <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 100%;">
                                    <?php echo $character['stats']['power'] ?>
                                </div>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="col-md-4">
        <div class="well">
            <table class="table table-condensed character-stats-table">
                <tbody>
                    <tr>
                        <td>
                            <span>Force</span>
                        </td>

                        <td>
                            <span><?php echo $character['stats']['str'] ?></span>
                        </td>
                    </tr>

                    <tr>
                        <td>
                            <span>Agilité</span>
                        </td>

                        <td>
                            <span><?php echo $character['stats']['agi'] ?></span>
                        </td>
                    </tr>

                    <tr>
                        <td>
                            <span>Intelligence</span>
                        </td>

                        <td>
                            <span><?php echo $character['stats']['int'] ?></span>
                        </td>
                    </tr>

                    <tr>
                        <td>
                            <span>Endurance</span>
                        </td>

                        <td>
                            <span><?php echo $character['stats']['sta'] ?></span>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="col-md-4">
        <div class="well">
            <table class="table table-condensed character-stats-table">
                <tbody>
                    <tr>
                        <td>
                            <span>Critique</span>
                        </td>
                        <td>
                            <span><?php echo round($character['stats']['crit'], 2) ?> %</span>
                        </td>
                    </tr>

                    <tr>
                        <td>
                            <span>Hâte</span>
                        </td>
                        <td>
                            <span><?php echo round($character['stats']['haste'], 2) ?> %</span>
                        </td>
                    </tr>

                    <tr>
                        <td>
                            <span>Maitrise</span>
                        </td>
                        <td>
                            <span><?php echo round($character['stats']['mastery'], 2) ?> %</span>
                        </td>
                    </tr>

                    <tr>
                        <td>
                            <span>Polyvalence</span>
                        </td>
                        <td>
                            <span><?php echo round($character['stats']['versatilityDamageDoneBonus'], 2) ?> %</span>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="well">
            <span>Graph kill boss raid 1</span>
        </div>
    </div>

    <div class="col-md-6">
        <div class="well">
            <span>Graph kill boss raid 2</span>
        </div>
    </div>
</div>

<?php require_once 'stop_html.php' ?>