<?php require_once 'start_html.php' ?>

<pre>
    <?php var_dump($character['progression']['raids'][35]['bosses']) ?>
</pre>

<div class="row character-header-row">
    <div class="col-md-8">
        <div class="well">
            <table>
                <tbody>
                    <tr>
                        <td rowspan="2">
                            <img class="img-thumbnail character-thumbnail" src="http://render-api-eu.worldofwarcraft.com/static-render/eu/<?php echo $character['thumbnail'] ?>" />
                        </td>

                        <td>
                            <span class="character-name"><?php echo $character['name'] ?></span>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <span class="character-guild"><?php echo $character['name'] ?></span>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="col-md-4">
        <div class="well">
            <table class="table table-condensed character-ressources-table">
                <tbody>
                    <tr>
                        <td width="100px">
                            <span>Level</span>
                        </td>
                        <td>
                            <div class="progress character-ilvl-progress">
                                <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 100%;">
                                    <?php echo $character['level'] ?>
                                </div>
                            </div>
                        </td>
                    </tr>

                    <tr>
                        <td width="100px">
                            <span>iLvl</span>
                        </td>
                        <td>
                            <div class="progress character-ilvl-progress">
                                <div class="progress-bar <?php echo 'power-' . $character['stats']['powerType'] ?>" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 100%;">
                                    <?php echo $character['items']['averageItemLevelEquipped'] ?>
                                </div>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="row character-stats-row">
    <div class="col-md-4">
        <div class="well">
            <table class="table table-condensed character-ressources-table">
                <tbody>
                    <tr>
                        <td width="100px">
                            <span>Vie</span>
                        </td>
                        <td>
                            <div class="progress character-ilvl-progress">
                                <div class="progress-bar power-health" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 100%;">
                                    <?php echo $character['stats']['health'] ?>
                                </div>
                            </div>
                        </td>
                    </tr>

                    <tr>
                        <td width="100px">
                            <span><?php echo $character['stats']['powerType'] ?></span>
                        </td>
                        <td>
                            <div class="progress character-ilvl-progress">
                                <div class="progress-bar <?php echo 'power-' . $character['stats']['powerType'] ?>" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 100%;">
                                    <?php echo $character['stats']['power'] ?>
                                </div>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="col-md-4">
        <div class="well">
            <?php echo html_primary_stats($character) ?>
        </div>
    </div>

    <div class="col-md-4">
        <div class="well">
            <?php echo html_secondary_stats($character) ?>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="well" id="graph_1">
            <div id="parent">
                <canvas id="myChart" width="100%" height="200"></canvas>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="well">
            <span>Graph kill boss raid 2</span>
        </div>
    </div>
</div>

<script>
    $(function() {
        var canvas = document.getElementById("myChart");
        var parent = document.getElementById("parent");
        var ctx = canvas.getContext("2d");

        canvas.width = parent.offsetWidth;
        canvas.height = parent.offsetHeight;

        var myChart = new Chart(ctx, {
            type: 'bar',
            options: {
                responsive: true,
                maintainAspectRatio: false
            },
            data: {
                labels: <?php echo json_encode($labels, true) ?>,
                datasets: [
                    {
                        label: '# of kill NM',
                        data: <?php echo json_encode($datas_nm, true) ?>,
                        backgroundColor: 'rgba(255, 99, 132, 1)',
                    }, {
                        label: '# of kill HM',
                        data: <?php echo json_encode($datas_hm, true) ?>,
                        backgroundColor: 'rgba(54, 162, 235, 1)',
                    }, {
                        label: '# of kill MM',
                        data: <?php echo json_encode($datas_mm, true) ?>,
                        backgroundColor: 'rgba(54, 162, 235, 1)',
                    },

                ],
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero:true
                        }
                    }]
                }
            }
        });
    });
</script>

<?php require_once 'stop_html.php' ?>

<?php

function html_primary_stats($character) {
    $primary_stats = array (
        'str' => 'Force',
        'agi' => 'Agilité',
        'int' => 'Intelligence',
        'sta' => 'Endurance',
    );

    $html = '';

    $html.= '<table class="table table-condensed character-stats-table">';
    $html.=     '<tbody>';

    foreach ($primary_stats as $stats => $stats_label) {
        $html.=     '<tr>';
        $html.=         '<td>';
        $html.=             '<span>' . $stats_label . '</span>';
        $html.=         '</td>';

        $html.=         '<td class="text-right">';
        $html.=             '<span>' . $character['stats'][$stats] . '</span>';
        $html.=         '</td>';
        $html.=     '</tr>';
    }

    $html.=     '</tbody>';
    $html.= ' </table>';

    return $html;
}

function html_secondary_stats($character) {
    $secondary_stats = array (
        'crit'                       => 'Critique',
        'haste'                      => 'Hâte',
        'mastery'                    => 'Maitrise',
        'versatilityDamageDoneBonus' => 'Polyvalence',
    );

    $html = '';

    $html.= '<table class="table table-condensed character-stats-table">';
    $html.=     '<tbody>';

    foreach ($secondary_stats as $stats => $stats_label) {
        $html.=     '<tr>';
        $html.=         '<td>';
        $html.=             '<span>' . $stats_label . '</span>';
        $html.=         '</td>';

        $html.=         '<td class="text-right">';
        $html.=             '<span>' . round($character['stats'][$stats], 2) . ' %</span>';
        $html.=         '</td>';
        $html.=     '</tr>';
    }

    $html.=     '</tbody>';
    $html.= ' </table>';

    return $html;
}