<?php require_once 'start_html.php'; ?>

<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <form class="form-horizontal clearfix" action="" method="POST">
            <div class="form-group">
                <label for="username" class="col-md-2 control-label">Nom d'utilisateur</label>
                <div class="col-md-10">
                    <input name="username" type="text" value="" class="form-control" placeholder="Nom d'utilisateur">
                </div>
            </div>

            <div class="form-group">
                <label  for="email" class="col-md-2 control-label">Adresse e-mail</label>
                <div class="col-md-10">
                    <input name="email" type="email" value="" class="form-control" placeholder="exemple@wxyz.com">
                </div>
            </div>

            <div class="form-group">
                <label for="password" class="col-md-2 control-label">Mot de passe</label>
                <div class="col-md-10">
                    <input name="password" type="password" value="" class="form-control">
                </div>
            </div>

            <div class="form-group">
                <label for="password_confirm" class="col-md-2 control-label">Confirmation mot de passe</label>
                <div class="col-md-10">
                    <input name="password_confirm" type="password" value="" class="form-control">
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-10 col-md-offset-2">
                    <button type="submit" class="btn btn-primary btn-block">Inscription</button>
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    $(function() {
        // Verification du champ username


        // Verification du champ email
        $('input[name=email]').on('change', function() {
            var regex = /^[-a-z0-9~!$%^&*_=+}{\'?]+(\.[-a-z0-9~!$%^&*_=+}{\'?]+)*@([a-z0-9_][-a-z0-9_]*(\.[-a-z0-9_]+)*\.(aero|arpa|biz|com|coop|edu|gov|info|int|mil|museum|name|net|org|pro|travel|mobi|[a-z][a-z])|([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}))(:[0-9]{1,5})?$/i;
            if(regex.test($('input[name=email]').val())) {
                $('input[name=email]').closest('.form-group').removeClass('has-error');
                $('input[name=email]').closest('.form-group').addClass('has-success');
            } else {
                $('input[name=email]').closest('.form-group').removeClass('has-success');
                $('input[name=email]').closest('.form-group').addClass('has-error');
            }
        });

        // Verification du champ password
        $('input[name=password]').on('change', function() {
            var regex = /^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$/g;
            if(regex.test($('input[name=password]').val())) {
                $('input[name=password]').closest('.form-group').removeClass('has-error');
                $('input[name=password]').closest('.form-group').addClass('has-success');
            } else {
                $('input[name=password]').closest('.form-group').removeClass('has-success');
                $('input[name=password]').closest('.form-group').addClass('has-error');
            }
        });

        // Verification du champ password confirm
        $('input[name=password_confirm]').on('change', function() {
            if ($('input[name=password_confirm]').val() != $('input[name=password]').val()) {
                $('input[name=password_confirm]').closest('.form-group').removeClass('has-success');
                $('input[name=password_confirm]').closest('.form-group').addClass('has-error');
            } else {
                $('input[name=password_confirm]').closest('.form-group').removeClass('has-error');
                $('input[name=password_confirm]').closest('.form-group').addClass('has-success');
            }
        })
    });
</script>

<?php require_once 'stop_html.php'; ?>